package student.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private Long qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.career
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private String career;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.data
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private Long data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.link
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.declaration
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private String declaration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.brother
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private String brother;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_at
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private Long createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.update_at
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    private Long updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID
     *
     * @return the value of student.ID
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param id the value for student.ID
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public Long getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setQq(Long qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.career
     *
     * @return the value of student.career
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.career
     *
     * @param career the value for student.career
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setCareer(String career) {
        this.career = career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.data
     *
     * @return the value of student.data
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public Long getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.data
     *
     * @param data the value for student.data
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setData(Long data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school
     *
     * @return the value of student.school
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school
     *
     * @param school the value for student.school
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.link
     *
     * @return the value of student.link
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.link
     *
     * @param link the value for student.link
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.declaration
     *
     * @return the value of student.declaration
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.declaration
     *
     * @param declaration the value for student.declaration
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setDeclaration(String declaration) {
        this.declaration = declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.brother
     *
     * @return the value of student.brother
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public String getBrother() {
        return brother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.brother
     *
     * @param brother the value for student.brother
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setBrother(String brother) {
        this.brother = brother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_at
     *
     * @return the value of student.create_at
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_at
     *
     * @param createAt the value for student.create_at
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.update_at
     *
     * @return the value of student.update_at
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.update_at
     *
     * @param updateAt the value for student.update_at
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", studentId=" + studentId +
                ", name='" + name + '\'' +
                ", qq=" + qq +
                ", career='" + career + '\'' +
                ", data=" + data +
                ", school='" + school + '\'' +
                ", link='" + link + '\'' +
                ", declaration='" + declaration + '\'' +
                ", brother='" + brother + '\'' +
                ", createAt=" + createAt +
                ", updateAt=" + updateAt +
                '}';
    }
}