package student.mapper;

import java.util.List;
import student.model.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    Long insert(Student student);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    List<Student> selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 05 18:39:44 CST 2019
     */
    int updateByPrimaryKey(Student record);

    long selectCountId();

    List<Student> selectName(Student student);

    List<Student> selectStudent(Student student);
}